"""Deterministic teaching examples. These are NOT model-generated responses."""
from .knowledge import HandbookIndex, get_event_update, build_rag_prompt

SAMPLE_QUESTION = ("Can three first-year students join the hackathon, "
                   "and where do we report today?")
STAGES = ["1 · LLM only", "2 · RAG", "3 · Tool + fixed workflow", "4 · ADK agent"]


def offline_example(stage: str, question: str = SAMPLE_QUESTION,
                    venue_override: str | None = None) -> dict:
    # Always disclose this is a scripted flow, even when the UI stage says agent.
    index = HandbookIndex()
    hits = index.search(question)
    trace = []
    if stage == STAGES[0]:
        answer = ('Scripted, deliberately unsupported example: "Yes. Report to Lab 4." '
                  'No handbook or notice was supplied. This is NOT a real model output.')
    elif stage == STAGES[1]:
        trace = [{"type": "retrieved", "passages": hits},
                 {"type": "prompt", "text": build_rag_prompt(question, hits)}]
        answer = ("Offline evidence viewer: the passages below may answer the rules question. "
                  "The handbook does not contain today's venue. No answer was generated by an LLM.")
    else:
        # A fixed route based on one teaching example; this is deliberately not an agent.
        event_name = "hackathon" if "hackathon" in question.lower() else "unknown event"
        notice = get_event_update(event_name, venue_override)
        trace = [{"type": "tool_call", "name": "search_handbook", "arguments": {"query": question}},
                 {"type": "tool_result", "name": "search_handbook", "result": hits},
                 {"type": "tool_call", "name": "latest_event", "arguments": {"event": event_name}},
                 {"type": "tool_result", "name": "latest_event", "result": notice}]
        answer = (f'Fixed workflow result: {notice["venue"]}, {notice["reporting_time"]}. '
                  'Read the retrieved passages for rules. No LLM selected these steps.'
                  if notice["status"] == "found" else
                  "No event notice found. Ask for the exact event name. This is a fixed workflow.")
    return {"answer": answer, "trace": trace, "mode": "Offline scripted walkthrough"}
